controllers:
    resource: ../../src/Controller/
    type: annotation
peremption_OF_create:
    path: /api/v1/charge/{OF}
    controller: App\Controller\ApiController:createPeremption
    methods: [POST]

peremption_OF_update:
    path: /api/v1/charge/{OF}
    controller: App\Controller\ApiController:modifPeremption
    methods: [UPDATE]
